### ISSUE TITLE
I couldn't get this library to build with nw-gyp for versions above 0.8.0

### ISSUE THREAD

**Issue by Harissa** [jmendeth/parport.js#1]
I think the API has changed so that this library doesn't build for versions over 0.8.0

**Comment by mildsunrise** [comment]
What API? Sorry, I have no experience with nw nor nw-gyp and I can't get it to install. What's the log?

**Comment by Harissa** [comment]
As far as I can see they've changed the API for node addons from v.0.8.0 to v.0.10.0
http://nodejs.org/api/addons.html
https://github.com/joyent/node/wiki/Api-changes-between-v0.8-and-v0.10

When you're building addons using nw-gyp you have to specify the version of node you want to use. If I use version .0.8.0 the build works fine. Any higher version and I get a series of errors which begin

node_modules\parport\src\v8u.hpp(85): error C2039: 'Arguments' : is not a member of 'v8' (..\src\binding.cc).

I can post the whole log if you like but its 400 lines long...

**Comment by mildsunrise** [comment]
Ah, you mean _those_ API changes. It's strange, I have node 0.10.25 and it builds correctly for me... It seems my install has a compatibility layer yours doesn't.

Anyway, I upgraded V8U which should have solved this problem. Can you verify?
(make sure it's version 1.1.2)

**Comment by Harissa** [comment]
npm install parport
npm ERR! Error: Invalid name: "test thing" 
Er, is this something you've added?

**Comment by mildsunrise** [comment]
Nope. I've only changed the `version` in package.json.

**Comment by Harissa** [comment]
Ok, I'm not getting the "test thing" error any more but it still won't build for versions greater than 0.8.0.
If I use  _nw-gyp rebuild --target=0.8.0_ it builds fine
If I use _nw-gyp rebuild --target=0.9.0_ I get a string of errors which start with
`..\node_modules\parport\src\version.hpp(44): error C2562: 'v8u::Version::NewInstance' : 'void' function returning a value (..\src\binding.cc).` This is a different v8u error than before.

You can test it yourself in node
Install nw-gyp using `npm install nw-gyp -g`
Install parport using `npm install parport`
then go into the parport folder rebuild it using
`nw-gyp rebuild --target=0.9.0`

**Comment by mildsunrise** [comment]
Your errors are not, as you pointed out, because of the API changes between Node 0.8 and 0.10.

These errors are part of the API changes between 0.10 and the upcoming 0.12, which are _not_ backwards compatible and aren't completely addressed now.

**Comment by mildsunrise** [comment]
Let me be clear on this: that 0.9.0 is the version of NW you're targeting, not the Node.JS equivalent (which would be 0.11.9).

**Comment by mildsunrise** [comment]
I've tried many times, I just don't have the time to adapt to all API changes for 0.11 (it's an unstable version).

Checkout master, and see if it works for you. Even if it works, it could break at any moment because the V8 API changes a lot. Sorry, I can't do anything until Node 0.12 is out. I'm closing this.
